// Cosmatch branded HTML email layout
// Hinge + The Pattern editorial — cream #FAF6F0, Georgia heading, system-ui body
// Saturn brandmark (růžová planeta + světle růžový prstenec, -18° tilt)
// Replaced ✦ glyph to differentiate from Gemini logo (User request 19/20. 5. 2026)

export function emailLayout(opts: { heading: string; body: string; ctaUrl?: string; ctaLabel?: string }) {
  const cta = opts.ctaUrl
    ? `<table role="presentation" cellpadding="0" cellspacing="0" border="0" style="margin: 24px 0;"><tr><td><a href="${opts.ctaUrl}" style="display: inline-block; background: #111827; color: #ffffff; text-decoration: none; padding: 14px 32px; border-radius: 9999px; font-weight: 600; font-size: 15px; font-family: -apple-system, BlinkMacSystemFont, system-ui, sans-serif;">${opts.ctaLabel ?? 'Otevřít Cosmatch'}</a></td></tr></table>`
    : ''
  return `<!DOCTYPE html><html lang="cs"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Cosmatch</title></head><body style="margin:0;padding:0;background:#FAF6F0;font-family:-apple-system,BlinkMacSystemFont,system-ui,sans-serif;color:#1f2937;"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="background:#FAF6F0;padding:40px 20px;"><tr><td align="center"><table role="presentation" width="560" cellpadding="0" cellspacing="0" border="0" style="max-width:560px;background:#fff;border-radius:24px;padding:48px 40px;box-shadow:0 2px 8px rgba(0,0,0,0.04);"><tr><td><p style="margin:0 0 24px;font-family:Georgia,serif;font-size:24px;font-weight:500;color:#111827;letter-spacing:-0.02em;">Cosmatch <svg width="26" height="20" viewBox="-50 -38 100 76" xmlns="http://www.w3.org/2000/svg" style="display:inline-block;vertical-align:middle;"><g transform="rotate(-18)"><ellipse cx="0" cy="0" rx="40" ry="7" fill="none" stroke="#f9a8d4" stroke-width="3.5"/></g><circle cx="0" cy="0" r="18" fill="#ec4899"/><g transform="rotate(-18)"><path d="M -40 0 A 40 7 0 0 0 40 0" fill="none" stroke="#f9a8d4" stroke-width="3.5"/></g></svg></p><h1 style="margin:0 0 24px;font-family:Georgia,serif;font-size:28px;line-height:1.15;font-weight:500;color:#111827;letter-spacing:-0.02em;">${opts.heading}</h1><div style="font-size:16px;line-height:1.7;color:#374151;">${opts.body}</div>${cta}</td></tr><tr><td style="border-top:1px solid #e5e7eb;padding-top:24px;margin-top:32px;"><p style="margin:24px 0 8px;font-size:12px;color:#9ca3af;line-height:1.5;">Cosmatch · Mgr. Ing. Simona Cibulková · IČO 08419531<br>Numerologická seznamka · Praha<br><a href="https://cosmatch.cz" style="color:#9ca3af;">cosmatch.cz</a> · <a href="mailto:ahoj@cosmatch.cz" style="color:#9ca3af;">ahoj@cosmatch.cz</a></p></td></tr></table></td></tr></table></body></html>`
}
